# Porta do microserviço de clientes
server.port=8081

# Conexão com o banco de clientes
spring.datasource.url=jdbc:postgresql://localhost:5432/db_clientes
spring.datasource.username=postgres
spring.datasource.password=Bruce@666
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect